routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('facebook',function(){
    return view('facebook');
});

Route::group(['prefix' => 'admin'],function (){
    Route::get('/', 'Admin\HomeController@index');
    Route::get('/donation/list','Admin\DonationController@donationList')->name('get.donations.list');
    Route::resource('/donation','Admin\DonationController');
    Route::get('/donation/image/{file}','Admin\DonationController@getImage')->name('donation.image');
    Route::get('/donation/verify-show/{id}','Admin\DonationController@verifyDonation')->name('verify.show');
});

Route::get('auth/facebook','FacebookController@redirectToFacebook');
Route::get('auth/facebook/callback','FacebookController@handleCallback');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/update/image/{file}','HomeController@getImage')->name('update.image');

//Route::get('/admin', 'HomeController@admin')->name('admin');
Route::get('/donation/success/{donate_id}','DonationController@donationSuccess')->name('donate.success');
Route::resource('/donate', 'DonationController');
Route::get('/donors', 'DonationController@showDonors')->name('show.donors');
Route::resource('/fundraising', 'FundraisingController');
Route::get('/account/image/{file}','FundraisingController@getImage')->name('account.image');
Route::get('/gcash', 'DonationController@gcash')->name('gcash');
Route::get('/bank', 'DonationController@bank')->name('bank');
Route::resource('/covid_data', 'CovidDataController');
Route::resource('/proof_donation', 'DonationProofController');
Route::get('/cases', 'CovidDataController@getCovidCasesChart')->name('covid.cases');
Route::resource('/update', 'UpdateController');
Route::get('/updates','FundraisingController@formUpdates')->name('updates.create');
Route::post('/updates/create','FundraisingController@storeUpdates')->name('updates.store');

app/Donation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Donation extends Model
{
    use SoftDeletes;

    protected $primaryKey = 'id';

    protected $fillable = ['user_id', 'amount', 'comment','hide_amount','hide_info','hide_comment','created_at'];
    protected $dates = ['deleted_at'];

    public function userData(){
        return $this->belongsTo('App\User','user_id');
    }

    public function getProof(){
        return $this->hasOne(DonationProof::class,'donation_id');
    }
}

app/Http/Controllers/Admin/DonationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Donation;
use App\DonationProof;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Contracts\DataTable;
use Yajra\DataTables\Facades\DataTables;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;

class DonationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('is_admin');
    }

    public function index()
    {
        return view('admin.donation.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.donation.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request->file('attachment2'));
//        dd($request->input());
        try{
            foreach ($request->input('for_insert') as $value){
//            insert user
                $user = new User();
                $user->name = ($request->input('donor'.$value) ? $request->input('donor'.$value) : 'Anonymous');
                $user->email = 'Anonymous'.User::getUserID().'@covaid.abcsytems.com.ph';
                $user->password = md5(rand(1,10000));
                $user->type = 2;
                $user->save();

//            insert donation
                $donation = new Donation();
                $donation->user_id = $user->id;
                $donation->amount = floatval(implode(explode(',',$request->input('amount'.$value))));
                $donation->save();

//            insert proof
                if($request->has('attachment'.$value)){
                    $base64_str = substr($request->file('attachment'.$value), strpos($request->file('attachment'.$value), ",")+1);
                    $image = base64_decode($base64_str);
                    $filename = "proof-".time().($donation->id).".png";
                    $path = storage_path('app/public/').$filename;
                    Image::make(file_get_contents($request->file('attachment'.$value)))->save($path);

                }else{
                    $filename= '';
                }
                $donationProof = new DonationProof();
                $donationProof->donation_id = $donation->id;
                $donationProof->attachment = $filename;
                $donationProof->donation_method = $request->input('donation_send'.$value);
                $donationProof->verified_by = Auth::user()->id;
                $donationProof->verified_date = today();
                $donationProof->save();
            }
            $response = array(
                'status' => 'success',
                'desc'  => 'Donations successfully created!'
            );
        }catch (\Exception $exception){
            $response = array(
                'status' => 'error',
                'desc'  => $exception->getMessage()
            );
        }
        return response()->json($response,200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $donor_details = DonationProof::where('id', $id)->first();
        return view('admin.donation.show',['donor_details' => $donor_details]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $proof_donation = DonationProof::findOrFail($id);
            $proof = DonationProof::where('id', $id)->update([
                'verified_by' => Auth::User()->id,
                'verified_date' => date('y-m-d',strtotime($request->input('date_verified'))),
                'donation_method' => $request->input('donation_send'),
            ]);
            $donate = Donation::where('id', $proof_donation->donorData->id)->update([
                'amount' => floatval(implode(explode(',',$request->input('verified_amount'))))
            ]);
            $response = array(
                'status' => 'success',
                'desc'  => 'Donations successfully created!',
                'reload' => true,
                'route' => null
            );
        }catch (\Exception $exception){
            $response = array(
                'status' => 'error',
                'desc'  => $exception->getMessage()
            );
        }
        return response()->json($response,200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function donationList(){
        $donations = Donation::all();
        return DataTables::of($donations)->addColumn('donation_id',function($model){
            return $model->id;
        })->addColumn('donor',function($model){
            return $model->userData->name;
        })->addColumn('amount',function($model){
            return number_format($model->amount,2);
        })->addColumn('date_donated',function($model){
            return date("F d, Y", strtotime($model->created_at));
        })->addColumn('status',function($model){
            return (is_null($model->getProof->verified_date) ? "For Verification" : "Verified") ;
        })->addColumn('action',function($model){
            return '<center>
                        <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                            <i class="fa fa-bars"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-center" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="'.route('donation.show',$model->getProof->id).'"><i class="fa fa-eye" aria-hidden="true"></i> View Record</a>
                            '.(is_null($model->getProof->verified_date) ? '<a class="dropdown-item popup_form" data-toggle="modal" title="'.$model->userData->name.' - ₱'.number_format($model->amount,2).'" href="" data-url="'.route('verify.show',$model->getProof->id).'" ><i class="fa fa-check" aria-hidden="true"></i> Verify Donation</a>' : "").'
                            <a class="dropdown-item" href=""><i class="fa fa-pencil" aria-hidden="true"></i> Edit Record</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item popup_form" data-toggle="modal" style="cursor:pointer" data-url="" title="Delete Invoice Record"><i class="fa fa-trash" aria-hidden="true"></i> Delete Record</a>
                        </div>
                    </div>
                    </center>';
        })->escapeColumns([])
            ->make(true);
    }

    public function getImage($id){
        try{
            $proof = DonationProof::findOrFail($id);
            $file = Storage::disk('public')->get($proof->attachment);
            return response($file,200);
        }catch (Exception $exception){
            $response = Common::catchError($exception);
        }
    }

    public function verifyDonation($id){
        $proof = DonationProof::findOrFail($id);
        return view('admin.donation.verification', ['id' => $id,'amount' => $proof->donorData->amount]);
    }
}

app/Http/Controllers/DonationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Donation;
use App\DonationProof;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use App\Mail\Donated;
use Illuminate\Support\Facades\Mail;
use Illuminate\Database\Eloquent\Builder;

class DonationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $user = auth()->user();
        return view('donate.index',['user' => $user]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            $user = User::all();
            if(count($user)!= 0){
                $user_data = DB::table('users')->orderby('id','desc')->first();
                $last_id = $user_data->id;
            }
            else{
                $last_id = 0;
            }
            if (Auth::check()){
                $user = Auth::user();
            }else{
                if($request->input('first_name')){
                    $name= $request->input('first_name').' '.$request->input('last_name');
                }
                else{
                    $name = 'Anonymous';
                }

                if($request->has('image')){
                    $id = DB::table('users')->orderby('id','desc')->first();
                    $base64_str = substr($request->image, strpos($request->image, ",")+1);
                    $image = base64_decode($base64_str);
                    $filename = "accounts-".time().(!$id?'1':$id->id+1).".png";
                    $path = storage_path('app/public/').$filename;
                    Image::make(file_get_contents($request->image))->save($path);
                }else{
                    $filename= null;
                }

                $user = User::create([
                    'name' => $name,
                    'email' => ($request->input('email') ? $request->input('email') : 'Anonymous'.((int)$last_id+1).'@covaid.abcsytems.com.ph' ),
                    'type' => 2,
                    'password' => Hash::make($request->input('email')),
                    'image' => $filename,
                ]);
                \auth()->login($user);
            }
            $donate = Donation::create([
                'user_id'       => $user->id,
                'amount'        => floatval(implode(explode(',',$request->input('amount')))),
                'comment'       => $request->input('comment'),
                'hide_amount'   => ($request->input('hide_amount') ? $request->input('hide_amount') : 0),
                'hide_info'     => ($request->input('hide_info') ? $request->input('hide_info') : 0),
                'hide_comment'  => ($request->input('hide_info') ? $request->input('hide_info') : 0)
            ]);

            $this->proofDonation($user->id,$request->attachment,$donate->id);

            //function for email
            // self::sendMail($user->email,$donate->id);
            $response = array(
                'status' => 'success',
                'reload' => true,
                'route' => route('donate.success',$donate->id),
                'desc'  => 'Account successfully created!'
            );

       

        return response()->json($response,200);
    }

    public function donationSuccess($id){
        $donation = Donation::findOrFail($id);
        return view('donate.success',['donation' => $donation]);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function sendMail($email,$id)
    {
        Mail::to($email)->queue(new Donated($id));
    }

    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function gcash()
    {
        return view('donate.gcash');
    }

    public function bank()
    {
        return view('donate.bank');
    }

    public function proofDonation($id, $attachment,$donate_id){
        if($attachment){
            $base64_str = substr($attachment, strpos($attachment, ",")+1);
            $image = base64_decode($base64_str);
            $filename = "proof-".time().($id).".png";
            $path = storage_path('app/public/').$filename;
            Image::make(file_get_contents($attachment))->save($path);

        }else{
            $filename= '';
        }

        $proof_query = new DonationProof([
            'donation_id'=> $donate_id,
            'attachment' => $filename
        ]);
        $proof_query->save();
    }

    public function showDonors()
    {
        $donors = Donation::whereHas('getProof',function (Builder $query ){
            $query->whereNotNull('verified_date');
        })
            ->selectRaw('SUM(amount) AS amount,user_id,created_at')
            ->groupBy('user_id','created_at')
            ->paginate(8);
//        dd($donors);
//        $donors = Donation::paginate(8);
        return view('donate.donors',['donors' => $donors]);
    }
}

resources/views/admin/donation/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container" style="padding-top:8em; padding-bottom:3em; ">
        <div class="container" style="padding-top:8em; padding-bottom:3em; ">

            <h4 class="form-head"></h4>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div align="right" style="margin: 0px 0px 20px 0px">
                        <a href="{{ route('donation.index') }}">
                            <button class="btn btn-secondary"><i class="fa fa-chevron-left" aria-hidden="true"></i> BACK</button></a>
                    </div>
                </div>
            </div>
            <form method="POST" action="{{ route('donation.store') }}" id="donation_form" class="form-horizontal" enctype="multipart/form-data">
                @csrf
                <div class="row justify-content-center">
                    <div class="col-md-12">

                        <table class="table table-striped table-bordered table-hover text-center table-mediascreen" id="donation_create_list">
                            <thead class="thead-dark">
                            <tr align="center">
                                <th width="15%">Action</th>
                                <th width="25%">Donor</th>
                                <th width="20%">Donation Amount</th>
                                <th width="20%">Donate Thru</th>
                                <th width="20%">Proof of Donation</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                    <button class="btn btn-primary" id="add_new"><span class="fa fa-plus"></span></button>
                                    <input type="hidden" name="for_insert[]" value="0">
                                </td>
                                <td>
                                    <input type="text" class="form-control" placeholder="Donor's Name (Optional)." name="donor0">
                                </td>
                                <td>
                                    <input type="text" class="form-control amount" placeholder="Amount in Peso" name="amount0">
                                </td>
                                <td>
                                    <select class="form-control" name="donation_send0">
                                        <option value="1">GCash</option>
                                        <option value="2">BPI</option>
                                        <option value="3">MetroBank</option>
                                        <option value="4">PayPal</option>
                                    </select>
                                </td>
                                <td>
                                    <input type="file" class="form-control" name="attachment0">
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group" align="right" >
                            <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> SUBMIT</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
@endsection
@push('scripts')
    <script>
        let rules = {
            amount0 : {
                required: true,
                min: 1
            },
        };
        $('#donation_form').registerFields(rules);
        let ctr = 1;
        $('#add_new').on('click',function (e) {
            e.preventDefault();
            let row = '<tr class="remove_row">' +
                '<td>' +
                '<button class="btn btn-danger remove" ><span class="fa fa-minus"></span></button>' +
                '<input type="hidden" name="for_insert[]" value="'+ctr+'">' +
                '</td>' +
                '<td>' +
                ' <input type="text" class="form-control" placeholder="Donor\'s Name (Optional)." name="donor'+ctr+'">' +
                '</td>' +
                '<td>' +
                '<input type="text" class="form-control amount" placeholder="Amount in Peso" name="amount'+ctr+'">' +
                '</td>' +
                '<td>' +
                    '<select class="form-control" name="donation_send'+ctr+'">'+
                        '<option value="1">GCash</option>'+
                        '<option value="2">BPI</option>'+
                        '<option value="3">MetroBank</option>'+
                        '<option value="4">PayPal</option>'+
                    '</select>'+
                '</td>' +
                '<td>' +
                '<input type="file" class="form-control" name="attachment'+ctr+'">' +
                '</td>' +
                '</tr>';
            $('#donation_create_list tbody').append(row);
            $('input[name="amount'+ctr+'"]').rules('add',{
                'required' : true,
                'min' : 1
            })
            ctr++;
        });
        $(document).on('click','.remove',function (e) {
            e.preventDefault();
            $(this).closest('tr').remove();
        });
    </script>
@endpush

resources/views/admin/donation/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container" style="padding-top:8em; padding-bottom:3em; ">

        <h4 class="form-head">Donors List</h4>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div align="right" style="margin: 0px 0px 20px 0px"><a href="{{ route('donation.create') }}"><button class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> CREATE</button></a></div>
                <table class="table table-striped table-bordered table-hover text-center table-mediascreen" id="donation_list">
                    <thead class="thead-dark">
                    <tr align="center">
                        <th width="15%">Donation No.</th>
                        <th width="25%">Donor</th>
                        <th width="15%">Amount</th>
                        <th width="10%">Date Donated</th>
                        <th width="20%">Status</th>
                        <th width="15%">Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $("#donation_list").DataTable({
            pagingType: "full_numbers",
            processing: true,
            serverSide: true,
            type: "GET",
            ajax:"{!! route('get.donations.list') !!}",
            columns:[
                {data: "donation_id","name":"donation_id","width":"15%",
                    className:"v-align text-center",
                },
                {data: "donor","name":"donor","width":"20%", className:"v-align text-center"},
                {data: "amount","name":"amount","width":"20%", className:"v-align text-center"},
                {data: "date_donated","name":"date_donated","width":"30%", className:"v-align text-center"},
                {data: "status","name":"status","width":"20%", className:"v-align text-center"},
                {data: "action","name":"action",orderable:false,searchable:false,"width":"15%"},
            ],
            select: {
                style: "multi"
            }
        });
    </script>
@endpush

resources/views/admin/donation/verification.blade.php
<form method="POST" action="{{ route('donation.update', $id) }}" id="verify-form" class="form-horizontal" enctype="multipart/form-data">
    @csrf
    <div class="errors"></div>
    <input type="hidden" name="_method" value="PUT" >
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">Date Verified:</label>
                    <div class="col-md-6">
                        <input id="date_verified" type="text" class="form-control datepicker" name="date_verified">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">Verified Amount:</label>
                    <div class="col-md-6">
                        <input id="date_verified" type="text" class="form-control amount" name="verified_amount" value="{{ $amount }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">Donation Thru:</label>
                    <div class="col-md-6">
                        <select class="form-control" name="donation_send">
                            <option value="1">GCash</option>
                            <option value="2">BPI</option>
                            <option value="3">MetroBank</option>
                            <option value="4">PayPal</option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">Verified By:</label>
                    <div class="col-md-6" align="left">
                        <p>{{ Auth::User()->name }}</p>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary button-medium">Confirm</button>
            </div>
        </div>
    </div>
</form>
<script>
$(function () {
    //function to load bootstrap datetimepicker
    $('.datepicker').datetimepicker({
        format: 'L'
    });
});

let rules = {
    date_verified : {
        required: true
    },
    verified_amount : {
        required: true
    },
    donation_send : {
        required: true
    }
};
$('#verify-form').registerFields(rules);
</script>